/* dot-theme tarafından üretildi — elle düzenleme. */
* {
    background: rgba({{ background_rgb }}, 0.7);
    primary: {{ accent }};
    primary-fixed: {{ mix accent bright_foreground 25% }};
    primary-fixed-dim: {{ accent }};
    on-primary: {{ background }};
    on-primary-fixed: {{ darker_background }};
    on-primary-fixed-variant: {{ mix accent background 50% }};
    primary-container: {{ mix accent background 70% }};
    on-primary-container: {{ bright_foreground }};
    secondary: {{ cyan }};
    secondary-fixed: {{ mix cyan bright_foreground 25% }};
    secondary-fixed-dim: {{ cyan }};
    on-secondary: {{ background }};
    on-secondary-fixed: {{ darker_background }};
    on-secondary-fixed-variant: {{ mix cyan background 50% }};
    secondary-container: {{ mix cyan background 70% }};
    on-secondary-container: {{ bright_foreground }};
    tertiary: {{ magenta }};
    tertiary-fixed: {{ mix magenta bright_foreground 25% }};
    tertiary-fixed-dim: {{ magenta }};
    on-tertiary: {{ background }};
    on-tertiary-fixed: {{ darker_background }};
    on-tertiary-fixed-variant: {{ mix magenta background 50% }};
    tertiary-container: {{ mix magenta background 70% }};
    on-tertiary-container: {{ bright_foreground }};
    error: {{ red }};
    on-error: {{ background }};
    error-container: {{ mix red background 60% }};
    on-error-container: {{ bright_red }};
    surface: {{ background }};
    on-surface: {{ foreground }};
    on-surface-variant: {{ light_foreground }};
    outline: {{ muted }};
    outline-variant: {{ selection }};
    shadow: #000000;
    scrim: #000000;
    inverse-surface: {{ foreground }};
    inverse-on-surface: {{ background }};
    inverse-primary: {{ mix accent background 40% }};
    surface-dim: {{ dark_background }};
    surface-bright: {{ lighter_background }};
    surface-container-lowest: {{ darker_background }};
    surface-container-low: {{ dark_background }};
    surface-container: {{ mix background foreground 8% }};
    surface-container-high: {{ mix background foreground 14% }};
    surface-container-highest: {{ mix background foreground 20% }};
}
