/* dot-theme tarafından üretildi — elle düzenleme. */
@define-color blur_background rgba({{ background_rgb }}, 0.3);
@define-color blur_background8 rgba({{ background_rgb }}, 0.8);

@define-color background {{ background }};
@define-color error {{ red }};
@define-color error_container {{ mix red background 60% }};
@define-color inverse_on_surface {{ background }};
@define-color inverse_primary {{ mix accent background 40% }};
@define-color inverse_surface {{ foreground }};
@define-color on_background {{ foreground }};
@define-color on_error {{ background }};
@define-color on_error_container {{ bright_red }};
@define-color on_primary {{ background }};
@define-color on_primary_container {{ bright_foreground }};
@define-color on_primary_fixed {{ darker_background }};
@define-color on_primary_fixed_variant {{ mix accent background 50% }};
@define-color on_secondary {{ background }};
@define-color on_secondary_container {{ bright_foreground }};
@define-color on_secondary_fixed {{ darker_background }};
@define-color on_secondary_fixed_variant {{ mix cyan background 50% }};
@define-color on_surface {{ foreground }};
@define-color on_surface_variant {{ light_foreground }};
@define-color on_tertiary {{ background }};
@define-color on_tertiary_container {{ bright_foreground }};
@define-color on_tertiary_fixed {{ darker_background }};
@define-color on_tertiary_fixed_variant {{ mix magenta background 50% }};
@define-color outline {{ muted }};
@define-color outline_variant {{ selection }};
@define-color primary {{ accent }};
@define-color primary_container {{ mix accent background 70% }};
@define-color primary_fixed {{ mix accent bright_foreground 25% }};
@define-color primary_fixed_dim {{ accent }};
@define-color scrim #000000;
@define-color secondary {{ cyan }};
@define-color secondary_container {{ mix cyan background 70% }};
@define-color secondary_fixed {{ mix cyan bright_foreground 25% }};
@define-color secondary_fixed_dim {{ cyan }};
@define-color shadow #000000;
@define-color source_color {{ accent }};
@define-color surface {{ background }};
@define-color surface_bright {{ lighter_background }};
@define-color surface_container {{ mix background foreground 8% }};
@define-color surface_container_high {{ mix background foreground 14% }};
@define-color surface_container_highest {{ mix background foreground 20% }};
@define-color surface_container_low {{ dark_background }};
@define-color surface_container_lowest {{ darker_background }};
@define-color surface_dim {{ dark_background }};
@define-color surface_tint {{ accent }};
@define-color surface_variant {{ selection }};
@define-color tertiary {{ magenta }};
@define-color tertiary_container {{ mix magenta background 70% }};
@define-color tertiary_fixed {{ mix magenta bright_foreground 25% }};
@define-color tertiary_fixed_dim {{ magenta }};
