-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "DP-1", mode = "2560x1440@179.999", position = "0x0", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-3", mode = "1920x1080@119.982", position = "2560x360", scale = 1, vrr = 0 })
